### ISSUE TITLE
User can load a chat between themselves and any user

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#148]
Since users load the IDs of all their connected users into HTML and requires those IDs to load a chat by querying Chats table, changing the value of the ID allows a user to load a chat with any user that exists in the database.

This requires both a backend validation on the Likes(?)/Blocks table for the ID passed as well as a frontend validation to load an error message if a user manipulates the chat ID values

**Comment by serena-zhu** [comment]
fd71a940548a2bb3cb24e9e5057e8700f66eca32 (also see issue #145)

Leaving this open for now since users can still edit the id field in the users-list <ul> in brower. Though backend validation ensures that they can only view chat history from users s/he can already access (both users liked each other and neither user blocked the other).
