### ISSUE TITLE
AJAX scripts do not work in static folder

### ISSUE THREAD

**Issue by jchung05** [serena-zhu/Matcha#24]
They simply do not reference correctly and my script.js generates a 500 internal server when being passed as a post to block_user and will not work. Serena's also running into this issue with her js script for likes.

There was a moment where I did a cache refresh and restarted the server and was able to resolve this issue but after it malfunctioned I was not able to recreate it again.

**Comment by jchung05** [comment]
2c4080290a6126194c7e62eab2a8d401c0d42d32

8d037e55a2d1684b476706b35566ad5652c13ca8

**Comment by serena-zhu** [comment]
Creating a block for scripts in layout.html {% block script %} and then adding the link to the script in the html file seems to work. 

I think the file was linked successfully the whole time but I was getting errors when testing the like button because I was accessing session['user_id'] in the script and that seemed to work when it was in the same html file but not when I move it to a designated .js file. 

We can reproduce the way I linked my script for block_user and see if that will solve the issue.
