### ISSUE TITLE
Display mutually liked users only for chats

### ISSUE THREAD

**Issue by serena-zhu** [serena-zhu/Matcha#62]
Chats page currently shows list of users liked by logged-in user, need to filter out users that have not liked back yet.

**Comment by jchung05** [comment]
The current query is executed in O(2N) by double iterating through the Likes table: once for the liked_id and again for the liked_by_id and then cross matching for a bidirectional like.

I am keeping this open because there is a more efficient O(N) approach to this issue which involves refactoring the Likes table to include a fourth boolean column 'connected' that would default false when user A likes user B but not vice versa. When user B likes user A, we query the Likes table for user A and find a record for user A, then update user A's boolean field to true and finally insert user B into the Likes table with the 'connected' column as True.

If you consider this query, the search time only ever takes a single pass through the table with the condition `'liked_by_id' = <current_user_id> AND connected = t` and is clearly faster but with the tradeoff of an additional search time deficiency when liking other users. It also requires that we refactor the table and all seeded test users in order to utilize.

The tradeoffs are reasonable and I feel we should discuss both implementations. Please advise

**Comment by serena-zhu** [comment]
Seems to work for now. Will refactor only if necessary.
